/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AccountType = IDL.Variant({
  'demo' : IDL.Null,
  'live' : IDL.Null,
});
export const TradingAccount = IDL.Record({
  'balance' : IDL.Float64,
  'accountId' : IDL.Nat,
  'owner' : IDL.Principal,
  'freeMargin' : IDL.Float64,
  'accountCode' : IDL.Text,
  'accountType' : AccountType,
  'currency' : IDL.Text,
  'margin' : IDL.Float64,
  'equity' : IDL.Float64,
});
export const InstrumentCategory = IDL.Variant({
  'forex' : IDL.Null,
  'stocks' : IDL.Null,
  'commodities' : IDL.Null,
  'crypto' : IDL.Null,
  'indices' : IDL.Null,
});
export const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Time = IDL.Int;
export const ChatConversation = IDL.Record({
  'userEmail' : IDL.Text,
  'lastMessageTime' : Time,
  'userId' : IDL.Principal,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
});
export const MarketInstrument = IDL.Record({
  'leverage' : IDL.Float64,
  'name' : IDL.Text,
  'bidPrice' : IDL.Float64,
  'lastUpdated' : Time,
  'askPrice' : IDL.Float64,
  'enabled' : IDL.Bool,
  'category' : InstrumentCategory,
  'spread' : IDL.Float64,
  'instrumentId' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'closed' : IDL.Null,
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
});
export const TradeOrder = IDL.Record({
  'status' : OrderStatus,
  'closeTime' : IDL.Opt(Time),
  'accountId' : IDL.Nat,
  'openPrice' : IDL.Float64,
  'takeProfit' : IDL.Float64,
  'profitLoss' : IDL.Opt(IDL.Float64),
  'orderType' : OrderType,
  'orderId' : IDL.Nat,
  'closePrice' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Float64,
  'instrumentId' : IDL.Nat,
  'openTime' : Time,
  'lotSize' : IDL.Float64,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'accountId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Nat,
});
export const KycStatus = IDL.Variant({
  'notSubmitted' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'created' : Time,
  'country' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'kycNotes' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'kycStatus' : KycStatus,
  'homeAddress' : IDL.Text,
  'accountType' : AccountType,
  'isBanned' : IDL.Bool,
  'phone' : IDL.Text,
  'kycDocumentUrl' : IDL.Opt(IDL.Text),
});
export const WithdrawalRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalRequestStatus,
  'requestId' : IDL.Nat,
  'accountId' : IDL.Nat,
  'bankDetails' : IDL.Text,
  'owner' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const BotConfig = IDL.Record({
  'depositFlowEnabled' : IDL.Bool,
  'tradeFlowEnabled' : IDL.Bool,
  'botName' : IDL.Text,
  'findProviderEnabled' : IDL.Bool,
  'supportFlowEnabled' : IDL.Bool,
  'greetingMessage' : IDL.Text,
  'voiceEnabled' : IDL.Bool,
  'rules' : IDL.Text,
});
export const CryptoDepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const CryptoDepositRequest = IDL.Record({
  'status' : CryptoDepositStatus,
  'depositId' : IDL.Nat,
  'accountId' : IDL.Nat,
  'owner' : IDL.Principal,
  'coin' : IDL.Text,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const CryptoWalletAddress = IDL.Record({
  'coin' : IDL.Text,
  'network' : IDL.Text,
  'address' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'profit' : IDL.Float64,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'imageData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'audioData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'senderPrincipal' : IDL.Principal,
  'timestamp' : Time,
  'isFromAdmin' : IDL.Bool,
  'senderEmail' : IDL.Text,
});
export const AppNotification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'owner' : IDL.Principal,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
});
export const PlatformSettings = IDL.Record({
  'cryptoHours' : IDL.Text,
  'minDeposit' : IDL.Float64,
  'maintenanceMode' : IDL.Bool,
  'defaultDemoBalance' : IDL.Float64,
  'maxWithdrawal' : IDL.Float64,
  'minWithdrawal' : IDL.Float64,
  'forexHours' : IDL.Text,
  'stocksHours' : IDL.Text,
  'maxDeposit' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStaffAdmin' : IDL.Func([IDL.Text], [], []),
  'adminCancelOrder' : IDL.Func([IDL.Nat], [], []),
  'approveCryptoDeposit' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'checkEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'closeOrder' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDemoAccount' : IDL.Func([], [TradingAccount], []),
  'createInstrument' : IDL.Func(
      [IDL.Text, IDL.Text, InstrumentCategory, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createLiveAccountPlaceholder' : IDL.Func([IDL.Text], [TradingAccount], []),
  'createOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        OrderType,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'createTradingAccount' : IDL.Func(
      [AccountType, IDL.Text],
      [TradingAccount],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'depositToDemoAccount' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(TradingAccount)], ['query']),
  'getAllChatConversations' : IDL.Func(
      [],
      [IDL.Vec(ChatConversation)],
      ['query'],
    ),
  'getAllInstruments' : IDL.Func([], [IDL.Vec(MarketInstrument)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getBotConfig' : IDL.Func([], [BotConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCryptoDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(CryptoDepositRequest)],
      ['query'],
    ),
  'getCryptoWalletAddresses' : IDL.Func(
      [],
      [IDL.Vec(CryptoWalletAddress)],
      ['query'],
    ),
  'getEmailRegistrations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getEnabledInstruments' : IDL.Func(
      [],
      [IDL.Vec(MarketInstrument)],
      ['query'],
    ),
  'getFinancialSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'revenue' : IDL.Float64,
          'totalWithdrawals' : IDL.Float64,
          'totalBalance' : IDL.Float64,
          'totalDeposits' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getFullLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getInstrumentByIdQuery' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MarketInstrument)],
      ['query'],
    ),
  'getInstrumentBySymbol' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketInstrument)],
      ['query'],
    ),
  'getOwnAccounts' : IDL.Func([], [IDL.Vec(TradingAccount)], ['query']),
  'getOwnChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getOwnCryptoDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(CryptoDepositRequest)],
      ['query'],
    ),
  'getOwnLeaderboardEntry' : IDL.Func(
      [],
      [IDL.Opt(LeaderboardEntry)],
      ['query'],
    ),
  'getOwnNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
  'getOwnOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'getOwnTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPlatformSettings' : IDL.Func([], [PlatformSettings], ['query']),
  'getStaffAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopNLeaderboardEntries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getUserAccounts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TradingAccount)],
      ['query'],
    ),
  'getUserChatMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(TradeOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailVerified' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStaffAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markConversationRead' : IDL.Func([IDL.Principal], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AccountType],
      [],
      [],
    ),
  'registerWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectCryptoDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeCryptoWalletAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeStaffAdmin' : IDL.Func([IDL.Text], [], []),
  'requestOtp' : IDL.Func([IDL.Text], [], []),
  'requestStaffOtp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetUserDemoBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'reviewKycDocument' : IDL.Func([IDL.Principal, KycStatus, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AccountType],
      [],
      [],
    ),
  'sendAdminReply' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [IDL.Nat],
      [],
    ),
  'sendAnnouncementToAll' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendAnnouncementToUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendChatMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8)), IDL.Opt(IDL.Vec(IDL.Nat8))],
      [IDL.Nat],
      [],
    ),
  'sendPasswordResetEmail' : IDL.Func([IDL.Text], [], []),
  'setBotConfig' : IDL.Func([BotConfig], [], []),
  'setCryptoWalletAddress' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setPlatformSettings' : IDL.Func([PlatformSettings], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitCryptoDepositRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitKycDocument' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'toggleInstrumentEnabled' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'updateAccountBalance' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'updateInstrumentLeverage' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'updateInstrumentPrices' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'upgradeUserAccountType' : IDL.Func([IDL.Principal, AccountType], [], []),
  'verifyEmailToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'verifyLoginPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'verifyRegistrationOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'verifyStaffOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AccountType = IDL.Variant({ 'demo' : IDL.Null, 'live' : IDL.Null });
  const TradingAccount = IDL.Record({
    'balance' : IDL.Float64,
    'accountId' : IDL.Nat,
    'owner' : IDL.Principal,
    'freeMargin' : IDL.Float64,
    'accountCode' : IDL.Text,
    'accountType' : AccountType,
    'currency' : IDL.Text,
    'margin' : IDL.Float64,
    'equity' : IDL.Float64,
  });
  const InstrumentCategory = IDL.Variant({
    'forex' : IDL.Null,
    'stocks' : IDL.Null,
    'commodities' : IDL.Null,
    'crypto' : IDL.Null,
    'indices' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Time = IDL.Int;
  const ChatConversation = IDL.Record({
    'userEmail' : IDL.Text,
    'lastMessageTime' : Time,
    'userId' : IDL.Principal,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
  });
  const MarketInstrument = IDL.Record({
    'leverage' : IDL.Float64,
    'name' : IDL.Text,
    'bidPrice' : IDL.Float64,
    'lastUpdated' : Time,
    'askPrice' : IDL.Float64,
    'enabled' : IDL.Bool,
    'category' : InstrumentCategory,
    'spread' : IDL.Float64,
    'instrumentId' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'closed' : IDL.Null,
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
  });
  const TradeOrder = IDL.Record({
    'status' : OrderStatus,
    'closeTime' : IDL.Opt(Time),
    'accountId' : IDL.Nat,
    'openPrice' : IDL.Float64,
    'takeProfit' : IDL.Float64,
    'profitLoss' : IDL.Opt(IDL.Float64),
    'orderType' : OrderType,
    'orderId' : IDL.Nat,
    'closePrice' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Float64,
    'instrumentId' : IDL.Nat,
    'openTime' : Time,
    'lotSize' : IDL.Float64,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'accountId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Nat,
  });
  const KycStatus = IDL.Variant({
    'notSubmitted' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'created' : Time,
    'country' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'kycNotes' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'kycStatus' : KycStatus,
    'homeAddress' : IDL.Text,
    'accountType' : AccountType,
    'isBanned' : IDL.Bool,
    'phone' : IDL.Text,
    'kycDocumentUrl' : IDL.Opt(IDL.Text),
  });
  const WithdrawalRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalRequestStatus,
    'requestId' : IDL.Nat,
    'accountId' : IDL.Nat,
    'bankDetails' : IDL.Text,
    'owner' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const BotConfig = IDL.Record({
    'depositFlowEnabled' : IDL.Bool,
    'tradeFlowEnabled' : IDL.Bool,
    'botName' : IDL.Text,
    'findProviderEnabled' : IDL.Bool,
    'supportFlowEnabled' : IDL.Bool,
    'greetingMessage' : IDL.Text,
    'voiceEnabled' : IDL.Bool,
    'rules' : IDL.Text,
  });
  const CryptoDepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const CryptoDepositRequest = IDL.Record({
    'status' : CryptoDepositStatus,
    'depositId' : IDL.Nat,
    'accountId' : IDL.Nat,
    'owner' : IDL.Principal,
    'coin' : IDL.Text,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const CryptoWalletAddress = IDL.Record({
    'coin' : IDL.Text,
    'network' : IDL.Text,
    'address' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'profit' : IDL.Float64,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'imageData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'audioData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'senderPrincipal' : IDL.Principal,
    'timestamp' : Time,
    'isFromAdmin' : IDL.Bool,
    'senderEmail' : IDL.Text,
  });
  const AppNotification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'owner' : IDL.Principal,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
  });
  const PlatformSettings = IDL.Record({
    'cryptoHours' : IDL.Text,
    'minDeposit' : IDL.Float64,
    'maintenanceMode' : IDL.Bool,
    'defaultDemoBalance' : IDL.Float64,
    'maxWithdrawal' : IDL.Float64,
    'minWithdrawal' : IDL.Float64,
    'forexHours' : IDL.Text,
    'stocksHours' : IDL.Text,
    'maxDeposit' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStaffAdmin' : IDL.Func([IDL.Text], [], []),
    'adminCancelOrder' : IDL.Func([IDL.Nat], [], []),
    'approveCryptoDeposit' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'checkEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'closeOrder' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDemoAccount' : IDL.Func([], [TradingAccount], []),
    'createInstrument' : IDL.Func(
        [IDL.Text, IDL.Text, InstrumentCategory, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createLiveAccountPlaceholder' : IDL.Func([IDL.Text], [TradingAccount], []),
    'createOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          OrderType,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'createTradingAccount' : IDL.Func(
        [AccountType, IDL.Text],
        [TradingAccount],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'depositToDemoAccount' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(TradingAccount)], ['query']),
    'getAllChatConversations' : IDL.Func(
        [],
        [IDL.Vec(ChatConversation)],
        ['query'],
      ),
    'getAllInstruments' : IDL.Func([], [IDL.Vec(MarketInstrument)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getBotConfig' : IDL.Func([], [BotConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCryptoDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(CryptoDepositRequest)],
        ['query'],
      ),
    'getCryptoWalletAddresses' : IDL.Func(
        [],
        [IDL.Vec(CryptoWalletAddress)],
        ['query'],
      ),
    'getEmailRegistrations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getEnabledInstruments' : IDL.Func(
        [],
        [IDL.Vec(MarketInstrument)],
        ['query'],
      ),
    'getFinancialSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'revenue' : IDL.Float64,
            'totalWithdrawals' : IDL.Float64,
            'totalBalance' : IDL.Float64,
            'totalDeposits' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getFullLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getInstrumentByIdQuery' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketInstrument)],
        ['query'],
      ),
    'getInstrumentBySymbol' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketInstrument)],
        ['query'],
      ),
    'getOwnAccounts' : IDL.Func([], [IDL.Vec(TradingAccount)], ['query']),
    'getOwnChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getOwnCryptoDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(CryptoDepositRequest)],
        ['query'],
      ),
    'getOwnLeaderboardEntry' : IDL.Func(
        [],
        [IDL.Opt(LeaderboardEntry)],
        ['query'],
      ),
    'getOwnNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
    'getOwnOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'getOwnTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPlatformSettings' : IDL.Func([], [PlatformSettings], ['query']),
    'getStaffAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopNLeaderboardEntries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getUserAccounts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TradingAccount)],
        ['query'],
      ),
    'getUserChatMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TradeOrder)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailVerified' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStaffAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markConversationRead' : IDL.Func([IDL.Principal], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AccountType,
        ],
        [],
        [],
      ),
    'registerWithPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectCryptoDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeCryptoWalletAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeStaffAdmin' : IDL.Func([IDL.Text], [], []),
    'requestOtp' : IDL.Func([IDL.Text], [], []),
    'requestStaffOtp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetUserDemoBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'reviewKycDocument' : IDL.Func(
        [IDL.Principal, KycStatus, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AccountType,
        ],
        [],
        [],
      ),
    'sendAdminReply' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [IDL.Nat],
        [],
      ),
    'sendAnnouncementToAll' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendAnnouncementToUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendChatMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8)), IDL.Opt(IDL.Vec(IDL.Nat8))],
        [IDL.Nat],
        [],
      ),
    'sendPasswordResetEmail' : IDL.Func([IDL.Text], [], []),
    'setBotConfig' : IDL.Func([BotConfig], [], []),
    'setCryptoWalletAddress' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setPlatformSettings' : IDL.Func([PlatformSettings], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitCryptoDepositRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitKycDocument' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'toggleInstrumentEnabled' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'updateAccountBalance' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'updateInstrumentLeverage' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'updateInstrumentPrices' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'upgradeUserAccountType' : IDL.Func([IDL.Principal, AccountType], [], []),
    'verifyEmailToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'verifyLoginPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'verifyRegistrationOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'verifyStaffOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };