/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'demo' : null } |
  { 'live' : null };
export interface AppNotification {
  'id' : bigint,
  'title' : string,
  'notifType' : string,
  'owner' : Principal,
  'body' : string,
  'isRead' : boolean,
  'timestamp' : Time,
}
export interface BotConfig {
  'depositFlowEnabled' : boolean,
  'tradeFlowEnabled' : boolean,
  'botName' : string,
  'findProviderEnabled' : boolean,
  'supportFlowEnabled' : boolean,
  'greetingMessage' : string,
  'voiceEnabled' : boolean,
  'rules' : string,
}
export interface ChatConversation {
  'userEmail' : string,
  'lastMessageTime' : Time,
  'userId' : Principal,
  'lastMessage' : string,
  'unreadCount' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'imageData' : [] | [Uint8Array],
  'audioData' : [] | [Uint8Array],
  'senderPrincipal' : Principal,
  'timestamp' : Time,
  'isFromAdmin' : boolean,
  'senderEmail' : string,
}
export interface CryptoDepositRequest {
  'status' : CryptoDepositStatus,
  'depositId' : bigint,
  'accountId' : bigint,
  'owner' : Principal,
  'coin' : string,
  'network' : string,
  'walletAddress' : string,
  'notes' : string,
  'timestamp' : Time,
  'amount' : number,
}
export type CryptoDepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CryptoWalletAddress {
  'coin' : string,
  'network' : string,
  'address' : string,
}
export type InstrumentCategory = { 'forex' : null } |
  { 'stocks' : null } |
  { 'commodities' : null } |
  { 'crypto' : null } |
  { 'indices' : null };
export type KycStatus = { 'notSubmitted' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface LeaderboardEntry {
  'principal' : [] | [Principal],
  'name' : string,
  'profit' : number,
}
export interface MarketInstrument {
  'leverage' : number,
  'name' : string,
  'bidPrice' : number,
  'lastUpdated' : Time,
  'askPrice' : number,
  'enabled' : boolean,
  'category' : InstrumentCategory,
  'spread' : number,
  'instrumentId' : bigint,
  'symbol' : string,
}
export type OrderStatus = { 'closed' : null } |
  { 'cancelled' : null } |
  { 'open' : null };
export type OrderType = { 'buy' : null } |
  { 'sell' : null };
export interface PlatformSettings {
  'cryptoHours' : string,
  'minDeposit' : number,
  'maintenanceMode' : boolean,
  'defaultDemoBalance' : number,
  'maxWithdrawal' : number,
  'minWithdrawal' : number,
  'forexHours' : string,
  'stocksHours' : string,
  'maxDeposit' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TradeOrder {
  'status' : OrderStatus,
  'closeTime' : [] | [Time],
  'accountId' : bigint,
  'openPrice' : number,
  'takeProfit' : number,
  'profitLoss' : [] | [number],
  'orderType' : OrderType,
  'orderId' : bigint,
  'closePrice' : [] | [number],
  'stopLoss' : number,
  'instrumentId' : bigint,
  'openTime' : Time,
  'lotSize' : number,
}
export interface TradingAccount {
  'balance' : number,
  'accountId' : bigint,
  'owner' : Principal,
  'freeMargin' : number,
  'accountCode' : string,
  'accountType' : AccountType,
  'currency' : string,
  'margin' : number,
  'equity' : number,
}
export interface Transaction {
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'accountId' : bigint,
  'timestamp' : Time,
  'amount' : number,
  'transactionId' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'created' : Time,
  'country' : string,
  'dateOfBirth' : string,
  'name' : string,
  'kycNotes' : [] | [string],
  'email' : string,
  'kycStatus' : KycStatus,
  'homeAddress' : string,
  'accountType' : AccountType,
  'isBanned' : boolean,
  'phone' : string,
  'kycDocumentUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : WithdrawalRequestStatus,
  'requestId' : bigint,
  'accountId' : bigint,
  'bankDetails' : string,
  'owner' : Principal,
  'notes' : string,
  'timestamp' : Time,
  'amount' : number,
}
export type WithdrawalRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStaffAdmin' : ActorMethod<[string], undefined>,
  'adminCancelOrder' : ActorMethod<[bigint], undefined>,
  'approveCryptoDeposit' : ActorMethod<[bigint], undefined>,
  'approveWithdrawalRequest' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'checkEmailRegistered' : ActorMethod<[string], boolean>,
  'closeOrder' : ActorMethod<[bigint, number], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDemoAccount' : ActorMethod<[], TradingAccount>,
  'createInstrument' : ActorMethod<
    [string, string, InstrumentCategory, number, number],
    bigint
  >,
  'createLiveAccountPlaceholder' : ActorMethod<[string], TradingAccount>,
  'createOrder' : ActorMethod<
    [bigint, bigint, OrderType, number, number, number, number],
    bigint
  >,
  'createTradingAccount' : ActorMethod<[AccountType, string], TradingAccount>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'depositToDemoAccount' : ActorMethod<[bigint, number], undefined>,
  'getAllAccounts' : ActorMethod<[], Array<TradingAccount>>,
  'getAllChatConversations' : ActorMethod<[], Array<ChatConversation>>,
  'getAllInstruments' : ActorMethod<[], Array<MarketInstrument>>,
  'getAllOrders' : ActorMethod<[], Array<TradeOrder>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getBotConfig' : ActorMethod<[], BotConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCryptoDepositRequests' : ActorMethod<[], Array<CryptoDepositRequest>>,
  'getCryptoWalletAddresses' : ActorMethod<[], Array<CryptoWalletAddress>>,
  'getEmailRegistrations' : ActorMethod<[], Array<string>>,
  'getEnabledInstruments' : ActorMethod<[], Array<MarketInstrument>>,
  'getFinancialSummary' : ActorMethod<
    [],
    {
      'revenue' : number,
      'totalWithdrawals' : number,
      'totalBalance' : number,
      'totalDeposits' : number,
    }
  >,
  'getFullLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getInstrumentByIdQuery' : ActorMethod<[bigint], [] | [MarketInstrument]>,
  'getInstrumentBySymbol' : ActorMethod<[string], [] | [MarketInstrument]>,
  'getOrCreateInstrument' : ActorMethod<[string, string, InstrumentCategory, number, number], bigint>,
  'getOwnAccounts' : ActorMethod<[], Array<TradingAccount>>,
  'getOwnChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getOwnCryptoDepositRequests' : ActorMethod<[], Array<CryptoDepositRequest>>,
  'getOwnLeaderboardEntry' : ActorMethod<[], [] | [LeaderboardEntry]>,
  'getOwnNotifications' : ActorMethod<[], Array<AppNotification>>,
  'getOwnOrders' : ActorMethod<[], Array<TradeOrder>>,
  'getOwnTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPlatformSettings' : ActorMethod<[], PlatformSettings>,
  'getStaffAdmins' : ActorMethod<[], Array<string>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopNLeaderboardEntries' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getUserAccounts' : ActorMethod<[Principal], Array<TradingAccount>>,
  'getUserChatMessages' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getUserOrders' : ActorMethod<[Principal], Array<TradeOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailVerified' : ActorMethod<[string], boolean>,
  'isStaffAdmin' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markConversationRead' : ActorMethod<[Principal], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string, string, AccountType],
    undefined
  >,
  'registerWithPassword' : ActorMethod<[string, string], undefined>,
  'rejectCryptoDeposit' : ActorMethod<[bigint, string], undefined>,
  'rejectWithdrawalRequest' : ActorMethod<[bigint, string], undefined>,
  'removeCryptoWalletAddress' : ActorMethod<[string, string], undefined>,
  'removeStaffAdmin' : ActorMethod<[string], undefined>,
  'requestOtp' : ActorMethod<[string], undefined>,
  'requestStaffOtp' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetPassword' : ActorMethod<[string, string], undefined>,
  'resetUserDemoBalance' : ActorMethod<[Principal, bigint], undefined>,
  'reviewKycDocument' : ActorMethod<[Principal, KycStatus, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, string, string, string, AccountType],
    undefined
  >,
  'sendAdminReply' : ActorMethod<
    [Principal, string, [] | [Uint8Array], [] | [Uint8Array]],
    bigint
  >,
  'sendAnnouncementToAll' : ActorMethod<[string, string], undefined>,
  'sendAnnouncementToUser' : ActorMethod<[string, string, string], undefined>,
  'sendChatMessage' : ActorMethod<
    [string, [] | [Uint8Array], [] | [Uint8Array]],
    bigint
  >,
  'sendPasswordResetEmail' : ActorMethod<[string], undefined>,
  'setBotConfig' : ActorMethod<[BotConfig], undefined>,
  'setCryptoWalletAddress' : ActorMethod<[string, string, string], undefined>,
  'setPlatformSettings' : ActorMethod<[PlatformSettings], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitCryptoDepositRequest' : ActorMethod<
    [bigint, string, string, number, string],
    bigint
  >,
  'submitKycDocument' : ActorMethod<[string, string], undefined>,
  'submitWithdrawalRequest' : ActorMethod<[bigint, number, string], bigint>,
  'toggleInstrumentEnabled' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateAccountBalance' : ActorMethod<[bigint, number], undefined>,
  'updateInstrumentLeverage' : ActorMethod<[bigint, number], undefined>,
  'updateInstrumentPrices' : ActorMethod<[string, number, number], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'upgradeUserAccountType' : ActorMethod<[Principal, AccountType], undefined>,
  'verifyEmailToken' : ActorMethod<[string], string>,
  'verifyLoginPassword' : ActorMethod<[string, string], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
  'verifyRegistrationOtp' : ActorMethod<[string, string], boolean>,
  'verifyStaffOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];