/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    principal?: Principal;
    name: string;
    profit: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ChatConversation {
    userEmail: string;
    lastMessageTime: Time;
    userId: Principal;
    lastMessage: string;
    unreadCount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MarketInstrument {
    leverage: number;
    name: string;
    bidPrice: number;
    lastUpdated: Time;
    askPrice: number;
    enabled: boolean;
    category: InstrumentCategory;
    spread: number;
    instrumentId: bigint;
    symbol: string;
}
export interface PlatformSettings {
    cryptoHours: string;
    minDeposit: number;
    maintenanceMode: boolean;
    defaultDemoBalance: number;
    maxWithdrawal: number;
    minWithdrawal: number;
    forexHours: string;
    stocksHours: string;
    maxDeposit: number;
}
export interface BotConfig {
    botName: string;
    greetingMessage: string;
    rules: string;
    voiceEnabled: boolean;
    findProviderEnabled: boolean;
    depositFlowEnabled: boolean;
    tradeFlowEnabled: boolean;
    supportFlowEnabled: boolean;
}
export interface Transaction {
    status: TransactionStatus;
    transactionType: TransactionType;
    accountId: bigint;
    timestamp: Time;
    amount: number;
    transactionId: bigint;
}
export interface TradeOrder {
    status: OrderStatus;
    closeTime?: Time;
    accountId: bigint;
    openPrice: number;
    takeProfit: number;
    profitLoss?: number;
    orderType: OrderType;
    orderId: bigint;
    closePrice?: number;
    stopLoss: number;
    instrumentId: bigint;
    openTime: Time;
    lotSize: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AppNotification {
    id: bigint;
    title: string;
    body: string;
    timestamp: Time;
    isRead: boolean;
    notifType: string;
    owner: Principal;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    imageData?: Uint8Array;
    audioData?: Uint8Array;
    senderPrincipal: Principal;
    timestamp: Time;
    isFromAdmin: boolean;
    senderEmail: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface TradingAccount {
    balance: number;
    accountId: bigint;
    owner: Principal;
    freeMargin: number;
    accountType: AccountType;
    currency: string;
    margin: number;
    equity: number;
}
export interface CryptoWalletAddress {
    coin: string;
    network: string;
    address: string;
}
export interface CryptoDepositRequest {
    status: CryptoDepositStatus;
    depositId: bigint;
    accountId: bigint;
    owner: Principal;
    coin: string;
    network: string;
    walletAddress: string;
    notes: string;
    timestamp: Time;
    amount: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface WithdrawalRequest {
    status: WithdrawalRequestStatus;
    requestId: bigint;
    accountId: bigint;
    bankDetails: string;
    owner: Principal;
    notes: string;
    timestamp: Time;
    amount: number;
}
export interface UserProfile {
    created: Time;
    country: string;
    dateOfBirth: string;
    name: string;
    kycNotes?: string;
    email: string;
    kycStatus: KycStatus;
    homeAddress: string;
    accountType: AccountType;
    isBanned: boolean;
    phone: string;
    kycDocumentUrl?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AccountType {
    demo = "demo",
    live = "live"
}
export enum CryptoDepositStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum InstrumentCategory {
    forex = "forex",
    stocks = "stocks",
    commodities = "commodities",
    crypto = "crypto",
    indices = "indices"
}
export enum KycStatus {
    notSubmitted = "notSubmitted",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    closed = "closed",
    cancelled = "cancelled",
    open = "open"
}
export enum OrderType {
    buy = "buy",
    sell = "sell"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addStaffAdmin(email: string): Promise<void>;
    adminCancelOrder(orderId: bigint): Promise<void>;
    approveCryptoDeposit(depositId: bigint): Promise<void>;
    approveWithdrawalRequest(requestId: bigint, notes: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal): Promise<void>;
    closeOrder(orderId: bigint, closePrice: number): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createInstrument(name: string, symbol: string, category: InstrumentCategory, bidPrice: number, askPrice: number): Promise<bigint>;
    createOrder(accountId: bigint, instrumentId: bigint, orderType: OrderType, lotSize: number, openPrice: number, stopLoss: number, takeProfit: number): Promise<bigint>;
    createTradingAccount(accountType: AccountType, currency: string): Promise<TradingAccount>;
    deleteUser(user: Principal): Promise<void>;
    depositToDemoAccount(accountId: bigint, amount: number): Promise<void>;
    getAllAccounts(): Promise<Array<TradingAccount>>;
    getAllChatConversations(): Promise<Array<ChatConversation>>;
    getAllInstruments(): Promise<Array<MarketInstrument>>;
    getAllOrders(): Promise<Array<TradeOrder>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCryptoDepositRequests(): Promise<Array<CryptoDepositRequest>>;
    getCryptoWalletAddresses(): Promise<Array<CryptoWalletAddress>>;
    getEnabledInstruments(): Promise<Array<MarketInstrument>>;
    getFinancialSummary(): Promise<{
        revenue: number;
        totalWithdrawals: number;
        totalBalance: number;
        totalDeposits: number;
    }>;
    getFullLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getInstrumentByIdQuery(instrumentId: bigint): Promise<MarketInstrument | null>;
    getInstrumentBySymbol(symbol: string): Promise<MarketInstrument | null>;
    getOwnAccounts(): Promise<Array<TradingAccount>>;
    getOwnChatMessages(): Promise<Array<ChatMessage>>;
    getOwnNotifications(): Promise<Array<AppNotification>>;
    getOwnCryptoDepositRequests(): Promise<Array<CryptoDepositRequest>>;
    getOwnLeaderboardEntry(): Promise<LeaderboardEntry | null>;
    getOwnOrders(): Promise<Array<TradeOrder>>;
    getOwnTransactions(): Promise<Array<Transaction>>;
    getBotConfig(): Promise<BotConfig>;
    getPlatformSettings(): Promise<PlatformSettings>;
    getStaffAdmins(): Promise<Array<string>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTopNLeaderboardEntries(n: bigint): Promise<Array<LeaderboardEntry>>;
    getUserAccounts(user: Principal): Promise<Array<TradingAccount>>;
    getUserChatMessages(userId: Principal): Promise<Array<ChatMessage>>;
    getUserOrders(user: Principal): Promise<Array<TradeOrder>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStaffAdmin(email: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markConversationRead(userId: Principal): Promise<void>;
    markNotificationsRead(): Promise<void>;
    registerUser(name: string, email: string, phone: string, dateOfBirth: string, country: string, homeAddress: string, accountType: AccountType): Promise<void>;
    rejectCryptoDeposit(depositId: bigint, notes: string): Promise<void>;
    rejectWithdrawalRequest(requestId: bigint, notes: string): Promise<void>;
    removeCryptoWalletAddress(coin: string, network: string): Promise<void>;
    removeStaffAdmin(email: string): Promise<void>;
    requestOtp(email: string): Promise<void>;
    requestStaffOtp(email: string): Promise<void>;
    resetUserDemoBalance(user: Principal, accountId: bigint): Promise<void>;
    reviewKycDocument(user: Principal, status: KycStatus, notes: string): Promise<void>;
    saveCallerUserProfile(name: string, email: string, phone: string, dateOfBirth: string, country: string, homeAddress: string, accountType: AccountType): Promise<void>;
    sendAdminReply(userId: Principal, content: string, imageData: Uint8Array | null, audioData: Uint8Array | null): Promise<bigint>;
    sendAnnouncementToAll(subject: string, body: string): Promise<void>;
    sendAnnouncementToUser(toEmail: string, subject: string, body: string): Promise<void>;
    sendChatMessage(content: string, imageData: Uint8Array | null, audioData: Uint8Array | null): Promise<bigint>;
    setCryptoWalletAddress(coin: string, network: string, address: string): Promise<void>;
    setBotConfig(config: BotConfig): Promise<void>;
    setPlatformSettings(settings: PlatformSettings): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitCryptoDepositRequest(accountId: bigint, coin: string, network: string, amount: number, walletAddress: string): Promise<bigint>;
    submitKycDocument(documentUrl: string, _documentType: string): Promise<void>;
    submitWithdrawalRequest(accountId: bigint, amount: number, bankDetails: string): Promise<bigint>;
    toggleInstrumentEnabled(instrumentId: bigint, enabled: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unbanUser(user: Principal): Promise<void>;
    updateAccountBalance(accountId: bigint, newBalance: number): Promise<void>;
    updateInstrumentLeverage(instrumentId: bigint, leverage: number): Promise<void>;
    updateInstrumentPrices(instrumentId: string, bidPrice: number, askPrice: number): Promise<void>;
    updateUserProfile(name: string, email: string, phone: string, dateOfBirth: string, country: string, homeAddress: string): Promise<void>;
    upgradeUserAccountType(user: Principal, accountType: AccountType): Promise<void>;
    verifyOtp(email: string, code: string): Promise<boolean>;
    verifyStaffOtp(email: string, code: string): Promise<boolean>;
}
import type { AppNotification as _AppNotification, AccountType as _AccountType, ChatMessage as _ChatMessage, CryptoDepositRequest as _CryptoDepositRequest, CryptoDepositStatus as _CryptoDepositStatus, InstrumentCategory as _InstrumentCategory, KycStatus as _KycStatus, LeaderboardEntry as _LeaderboardEntry, MarketInstrument as _MarketInstrument, OrderStatus as _OrderStatus, OrderType as _OrderType, StripeSessionStatus as _StripeSessionStatus, Time as _Time, TradeOrder as _TradeOrder, TradingAccount as _TradingAccount, Transaction as _Transaction, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, WithdrawalRequestStatus as _WithdrawalRequestStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addStaffAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffAdmin(arg0);
            return result;
        }
    }
    async adminCancelOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelOrder(arg0);
            return result;
        }
    }
    async approveCryptoDeposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCryptoDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCryptoDeposit(arg0);
            return result;
        }
    }
    async approveWithdrawalRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async closeOrder(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeOrder(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createInstrument(arg0: string, arg1: string, arg2: InstrumentCategory, arg3: number, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInstrument(arg0, arg1, to_candid_InstrumentCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInstrument(arg0, arg1, to_candid_InstrumentCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createOrder(arg0: bigint, arg1: bigint, arg2: OrderType, arg3: number, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, to_candid_OrderType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, to_candid_OrderType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createTradingAccount(arg0: AccountType, arg1: string): Promise<TradingAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.createTradingAccount(to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_TradingAccount_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTradingAccount(to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_TradingAccount_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async depositToDemoAccount(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositToDemoAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositToDemoAccount(arg0, arg1);
            return result;
        }
    }
    async getAllAccounts(): Promise<Array<TradingAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccounts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccounts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChatConversations(): Promise<Array<ChatConversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChatConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChatConversations();
            return result;
        }
    }
    async getAllInstruments(): Promise<Array<MarketInstrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstruments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstruments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoDepositRequests(): Promise<Array<CryptoDepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoDepositRequests();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoDepositRequests();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoWalletAddresses(): Promise<Array<CryptoWalletAddress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoWalletAddresses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoWalletAddresses();
            return result;
        }
    }
    async getEnabledInstruments(): Promise<Array<MarketInstrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledInstruments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledInstruments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialSummary(): Promise<{
        revenue: number;
        totalWithdrawals: number;
        totalBalance: number;
        totalDeposits: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummary();
            return result;
        }
    }
    async getFullLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullLeaderboard();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullLeaderboard();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstrumentByIdQuery(arg0: bigint): Promise<MarketInstrument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstrumentByIdQuery(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstrumentByIdQuery(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstrumentBySymbol(arg0: string): Promise<MarketInstrument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstrumentBySymbol(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstrumentBySymbol(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnAccounts(): Promise<Array<TradingAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnAccounts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnAccounts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnChatMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnChatMessages();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnChatMessages();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnNotifications(): Promise<Array<AppNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnNotifications();
                return result.map((n: any) => ({ id: n.id, title: n.title, body: n.body, timestamp: n.timestamp, isRead: n.isRead, notifType: n.notifType, owner: n.owner }));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnNotifications();
            return result.map((n: any) => ({ id: n.id, title: n.title, body: n.body, timestamp: n.timestamp, isRead: n.isRead, notifType: n.notifType, owner: n.owner }));
        }
    }
    async getOwnCryptoDepositRequests(): Promise<Array<CryptoDepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnCryptoDepositRequests();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnCryptoDepositRequests();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnLeaderboardEntry(): Promise<LeaderboardEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnLeaderboardEntry();
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnLeaderboardEntry();
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnOrders(): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnTransactions();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnTransactions();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBotConfig(): Promise<BotConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBotConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBotConfig();
            return result;
        }
    }
    async getPlatformSettings(): Promise<PlatformSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformSettings();
            return result;
        }
    }
    async getStaffAdmins(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffAdmins();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopNLeaderboardEntries(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopNLeaderboardEntries(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopNLeaderboardEntries(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccounts(arg0: Principal): Promise<Array<TradingAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccounts(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccounts(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserChatMessages(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserChatMessages(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserChatMessages(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStaffAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStaffAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStaffAdmin(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markConversationRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationRead(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: AccountType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async rejectCryptoDeposit(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCryptoDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCryptoDeposit(arg0, arg1);
            return result;
        }
    }
    async rejectWithdrawalRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async removeCryptoWalletAddress(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCryptoWalletAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCryptoWalletAddress(arg0, arg1);
            return result;
        }
    }
    async removeStaffAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStaffAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStaffAdmin(arg0);
            return result;
        }
    }
    async requestOtp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestOtp(arg0);
            return result;
        }
    }
    async requestStaffOtp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestStaffOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestStaffOtp(arg0);
            return result;
        }
    }
    async resetUserDemoBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserDemoBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserDemoBalance(arg0, arg1);
            return result;
        }
    }
    async reviewKycDocument(arg0: Principal, arg1: KycStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewKycDocument(arg0, to_candid_KycStatus_n74(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewKycDocument(arg0, to_candid_KycStatus_n74(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: AccountType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async sendAdminReply(arg0: Principal, arg1: string, arg2: Uint8Array | null, arg3: Uint8Array | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAdminReply(arg0, arg1, to_candid_opt_n76(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n76(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAdminReply(arg0, arg1, to_candid_opt_n76(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n76(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async sendAnnouncementToAll(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAnnouncementToAll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAnnouncementToAll(arg0, arg1);
            return result;
        }
    }
    async sendAnnouncementToUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAnnouncementToUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAnnouncementToUser(arg0, arg1, arg2);
            return result;
        }
    }
    async sendChatMessage(arg0: string, arg1: Uint8Array | null, arg2: Uint8Array | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, to_candid_opt_n76(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n76(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, to_candid_opt_n76(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n76(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setCryptoWalletAddress(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCryptoWalletAddress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCryptoWalletAddress(arg0, arg1, arg2);
            return result;
        }
    }
    async setBotConfig(arg0: BotConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBotConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBotConfig(arg0);
            return result;
        }
    }
    async setPlatformSettings(arg0: PlatformSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlatformSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlatformSettings(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitCryptoDepositRequest(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCryptoDepositRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCryptoDepositRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitKycDocument(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKycDocument(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKycDocument(arg0, arg1);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: bigint, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleInstrumentEnabled(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleInstrumentEnabled(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleInstrumentEnabled(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async updateAccountBalance(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccountBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccountBalance(arg0, arg1);
            return result;
        }
    }
    async updateInstrumentLeverage(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstrumentLeverage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstrumentLeverage(arg0, arg1);
            return result;
        }
    }
    async updateInstrumentPrices(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstrumentPrices(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstrumentPrices(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async upgradeUserAccountType(arg0: Principal, arg1: AccountType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeUserAccountType(arg0, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeUserAccountType(arg0, to_candid_AccountType_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
    async verifyStaffOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyStaffOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyStaffOtp(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AccountType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_CryptoDepositRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CryptoDepositRequest): CryptoDepositRequest {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_CryptoDepositStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CryptoDepositStatus): CryptoDepositStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_InstrumentCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InstrumentCategory): InstrumentCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_KycStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycStatus): KycStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_MarketInstrument_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketInstrument): MarketInstrument {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOrder_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOrder): TradeOrder {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TradingAccount_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingAccount): TradingAccount {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequestStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequestStatus): WithdrawalRequestStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketInstrument]): MarketInstrument | null {
    return value.length === 0 ? null : from_candid_MarketInstrument_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaderboardEntry]): LeaderboardEntry | null {
    return value.length === 0 ? null : from_candid_LeaderboardEntry_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    accountId: bigint;
    owner: Principal;
    freeMargin: number;
    accountType: _AccountType;
    currency: string;
    margin: number;
    equity: number;
}): {
    balance: number;
    accountId: bigint;
    owner: Principal;
    freeMargin: number;
    accountType: AccountType;
    currency: string;
    margin: number;
    equity: number;
} {
    return {
        balance: value.balance,
        accountId: value.accountId,
        owner: value.owner,
        freeMargin: value.freeMargin,
        accountType: from_candid_AccountType_n18(_uploadFile, _downloadFile, value.accountType),
        currency: value.currency,
        margin: value.margin,
        equity: value.equity
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leverage: number;
    name: string;
    bidPrice: number;
    lastUpdated: _Time;
    askPrice: number;
    enabled: boolean;
    category: _InstrumentCategory;
    spread: number;
    instrumentId: bigint;
    symbol: string;
}): {
    leverage: number;
    name: string;
    bidPrice: number;
    lastUpdated: Time;
    askPrice: number;
    enabled: boolean;
    category: InstrumentCategory;
    spread: number;
    instrumentId: bigint;
    symbol: string;
} {
    return {
        leverage: value.leverage,
        name: value.name,
        bidPrice: value.bidPrice,
        lastUpdated: value.lastUpdated,
        askPrice: value.askPrice,
        enabled: value.enabled,
        category: from_candid_InstrumentCategory_n24(_uploadFile, _downloadFile, value.category),
        spread: value.spread,
        instrumentId: value.instrumentId,
        symbol: value.symbol
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    closeTime: [] | [_Time];
    accountId: bigint;
    openPrice: number;
    takeProfit: number;
    profitLoss: [] | [number];
    orderType: _OrderType;
    orderId: bigint;
    closePrice: [] | [number];
    stopLoss: number;
    instrumentId: bigint;
    openTime: _Time;
    lotSize: number;
}): {
    status: OrderStatus;
    closeTime?: Time;
    accountId: bigint;
    openPrice: number;
    takeProfit: number;
    profitLoss?: number;
    orderType: OrderType;
    orderId: bigint;
    closePrice?: number;
    stopLoss: number;
    instrumentId: bigint;
    openTime: Time;
    lotSize: number;
} {
    return {
        status: from_candid_OrderStatus_n29(_uploadFile, _downloadFile, value.status),
        closeTime: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.closeTime)),
        accountId: value.accountId,
        openPrice: value.openPrice,
        takeProfit: value.takeProfit,
        profitLoss: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.profitLoss)),
        orderType: from_candid_OrderType_n33(_uploadFile, _downloadFile, value.orderType),
        orderId: value.orderId,
        closePrice: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.closePrice)),
        stopLoss: value.stopLoss,
        instrumentId: value.instrumentId,
        openTime: value.openTime,
        lotSize: value.lotSize
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    transactionType: _TransactionType;
    accountId: bigint;
    timestamp: _Time;
    amount: number;
    transactionId: bigint;
}): {
    status: TransactionStatus;
    transactionType: TransactionType;
    accountId: bigint;
    timestamp: Time;
    amount: number;
    transactionId: bigint;
} {
    return {
        status: from_candid_TransactionStatus_n38(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n40(_uploadFile, _downloadFile, value.transactionType),
        accountId: value.accountId,
        timestamp: value.timestamp,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    country: string;
    dateOfBirth: string;
    name: string;
    kycNotes: [] | [string];
    email: string;
    kycStatus: _KycStatus;
    homeAddress: string;
    accountType: _AccountType;
    isBanned: boolean;
    phone: string;
    kycDocumentUrl: [] | [string];
}): {
    created: Time;
    country: string;
    dateOfBirth: string;
    name: string;
    kycNotes?: string;
    email: string;
    kycStatus: KycStatus;
    homeAddress: string;
    accountType: AccountType;
    isBanned: boolean;
    phone: string;
    kycDocumentUrl?: string;
} {
    return {
        created: value.created,
        country: value.country,
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        kycNotes: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.kycNotes)),
        email: value.email,
        kycStatus: from_candid_KycStatus_n47(_uploadFile, _downloadFile, value.kycStatus),
        homeAddress: value.homeAddress,
        accountType: from_candid_AccountType_n18(_uploadFile, _downloadFile, value.accountType),
        isBanned: value.isBanned,
        phone: value.phone,
        kycDocumentUrl: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.kycDocumentUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WithdrawalRequestStatus;
    requestId: bigint;
    accountId: bigint;
    bankDetails: string;
    owner: Principal;
    notes: string;
    timestamp: _Time;
    amount: number;
}): {
    status: WithdrawalRequestStatus;
    requestId: bigint;
    accountId: bigint;
    bankDetails: string;
    owner: Principal;
    notes: string;
    timestamp: Time;
    amount: number;
} {
    return {
        status: from_candid_WithdrawalRequestStatus_n52(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        accountId: value.accountId,
        bankDetails: value.bankDetails,
        owner: value.owner,
        notes: value.notes,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CryptoDepositStatus;
    depositId: bigint;
    accountId: bigint;
    owner: Principal;
    coin: string;
    network: string;
    walletAddress: string;
    notes: string;
    timestamp: _Time;
    amount: number;
}): {
    status: CryptoDepositStatus;
    depositId: bigint;
    accountId: bigint;
    owner: Principal;
    coin: string;
    network: string;
    walletAddress: string;
    notes: string;
    timestamp: Time;
    amount: number;
} {
    return {
        status: from_candid_CryptoDepositStatus_n60(_uploadFile, _downloadFile, value.status),
        depositId: value.depositId,
        accountId: value.accountId,
        owner: value.owner,
        coin: value.coin,
        network: value.network,
        walletAddress: value.walletAddress,
        notes: value.notes,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: [] | [Principal];
    name: string;
    profit: number;
}): {
    principal?: Principal;
    name: string;
    profit: number;
} {
    return {
        principal: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.principal)),
        name: value.name,
        profit: value.profit
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    imageData: [] | [Uint8Array];
    audioData: [] | [Uint8Array];
    senderPrincipal: Principal;
    timestamp: _Time;
    isFromAdmin: boolean;
    senderEmail: string;
}): {
    id: bigint;
    content: string;
    imageData?: Uint8Array;
    audioData?: Uint8Array;
    senderPrincipal: Principal;
    timestamp: Time;
    isFromAdmin: boolean;
    senderEmail: string;
} {
    return {
        id: value.id,
        content: value.content,
        imageData: record_opt_to_undefined(from_candid_opt_n69(_uploadFile, _downloadFile, value.imageData)),
        audioData: record_opt_to_undefined(from_candid_opt_n69(_uploadFile, _downloadFile, value.audioData)),
        senderPrincipal: value.senderPrincipal,
        timestamp: value.timestamp,
        isFromAdmin: value.isFromAdmin,
        senderEmail: value.senderEmail
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_tuple_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n44(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    demo: null;
} | {
    live: null;
}): AccountType {
    return "demo" in value ? AccountType.demo : "live" in value ? AccountType.live : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    stocks: null;
} | {
    commodities: null;
} | {
    crypto: null;
} | {
    indices: null;
}): InstrumentCategory {
    return "forex" in value ? InstrumentCategory.forex : "stocks" in value ? InstrumentCategory.stocks : "commodities" in value ? InstrumentCategory.commodities : "crypto" in value ? InstrumentCategory.crypto : "indices" in value ? InstrumentCategory.indices : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    cancelled: null;
} | {
    open: null;
}): OrderStatus {
    return "closed" in value ? OrderStatus.closed : "cancelled" in value ? OrderStatus.cancelled : "open" in value ? OrderStatus.open : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderType {
    return "buy" in value ? OrderType.buy : "sell" in value ? OrderType.sell : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
}): TransactionType {
    return "deposit" in value ? TransactionType.deposit : "withdrawal" in value ? TransactionType.withdrawal : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notSubmitted: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): KycStatus {
    return "notSubmitted" in value ? KycStatus.notSubmitted : "pending" in value ? KycStatus.pending : "approved" in value ? KycStatus.approved : "rejected" in value ? KycStatus.rejected : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CryptoDepositStatus {
    return "pending" in value ? CryptoDepositStatus.pending : "approved" in value ? CryptoDepositStatus.approved : "rejected" in value ? CryptoDepositStatus.rejected : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n73(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradingAccount>): Array<TradingAccount> {
    return value.map((x)=>from_candid_TradingAccount_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketInstrument>): Array<MarketInstrument> {
    return value.map((x)=>from_candid_MarketInstrument_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeOrder>): Array<TradeOrder> {
    return value.map((x)=>from_candid_TradeOrder_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CryptoDepositRequest>): Array<CryptoDepositRequest> {
    return value.map((x)=>from_candid_CryptoDepositRequest_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n67(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_InstrumentCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstrumentCategory): _InstrumentCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_KycStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycStatus): _KycStatus {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Uint8Array | null): [] | [Uint8Array] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstrumentCategory): {
    forex: null;
} | {
    stocks: null;
} | {
    commodities: null;
} | {
    crypto: null;
} | {
    indices: null;
} {
    return value == InstrumentCategory.forex ? {
        forex: null
    } : value == InstrumentCategory.stocks ? {
        stocks: null
    } : value == InstrumentCategory.commodities ? {
        commodities: null
    } : value == InstrumentCategory.crypto ? {
        crypto: null
    } : value == InstrumentCategory.indices ? {
        indices: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderType.buy ? {
        buy: null
    } : value == OrderType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    demo: null;
} | {
    live: null;
} {
    return value == AccountType.demo ? {
        demo: null
    } : value == AccountType.live ? {
        live: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycStatus): {
    notSubmitted: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == KycStatus.notSubmitted ? {
        notSubmitted: null
    } : value == KycStatus.pending ? {
        pending: null
    } : value == KycStatus.approved ? {
        approved: null
    } : value == KycStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
